-- PostgreSQL-compatible schema

-- Tables (IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    AADHAAR_NO VARCHAR(12) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_NO INT PRIMARY KEY,
    USER_ID INT,
    ACCOUNT_TYPE VARCHAR(20) DEFAULT 'SAVINGS' CHECK (ACCOUNT_TYPE IN ('SAVINGS', 'CHECKING', 'LOAN')),
    BALANCE DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'BLOCKED', 'CLOSED')),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID SERIAL PRIMARY KEY,
    SENDER_ACCOUNT INT NULL,
    RECEIVER_ACCOUNT INT NULL,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    TX_TYPE VARCHAR(20) NOT NULL CHECK (TX_TYPE IN ('TRANSFER', 'DEPOSIT', 'WITHDRAWAL')),
    REMARK VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SENDER_ACCOUNT) REFERENCES ACCOUNTS(ACCOUNT_NO)
);

CREATE TABLE IF NOT EXISTS LOAN_REQUESTS (
    ID SERIAL PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    LOAN_TYPE VARCHAR(50) NOT NULL,
    LOAN_AMOUNT DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Migration: add LOAN_AMOUNT column if table already existed without it (PostgreSQL-compatible)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'loan_requests' AND column_name = 'loan_amount'
    ) THEN
        ALTER TABLE LOAN_REQUESTS ADD COLUMN LOAN_AMOUNT DECIMAL(15, 2) NOT NULL DEFAULT 0.00;
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS PASSWORD_RESET_OTP (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    OTP VARCHAR(6) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT TIMESTAMP NOT NULL
);